### ISSUE TITLE
Strange errors.. is this where i go to ask for help?

### ISSUE THREAD

**Issue by NinjaBoyLao** [wedr2/Guide#1]
Hi wedr, i'm having an issue. i don't get any squiggly lines at the tricky part, but im not sure what i did wrong, because when i try to build im getting this:
![capture](https://cloud.githubusercontent.com/assets/16899151/16031019/cefd33ae-31c4-11e6-8ae9-e4ba4de7a7c8.PNG)

**Comment by wedr2** [comment]
Hello NinjaBoyLao,

Sorry for not responding earlier, as I have things to do. Can you tell me what guide are you following? The first guide? or the Second guide?

The first guide is "Setting up VS2015 from scratch", and the second guide is "Setting VS2015 for CIA".

**Comment by NinjaBoyLao** [comment]
Alright, ill get back to you with the screenshots. I was follow the first guide, thanks for replying

**Comment by NinjaBoyLao** [comment]
![sctrkug](https://cloud.githubusercontent.com/assets/16899151/16172211/7b41c4b0-3551-11e6-94fe-cc6e4acfecfc.PNG)
![hjdyresxthehdxtj](https://cloud.githubusercontent.com/assets/16899151/16172212/7ffdc9ae-3551-11e6-9031-bf301904307c.PNG)
![nhjyhfxythdzxr](https://cloud.githubusercontent.com/assets/16899151/16172213/84c03d78-3551-11e6-9178-4651e67b45ec.PNG)

**Comment by wedr2** [comment]
Oh, your "/Source" folder needs to be lowercase. It should be: /**s**ource, not /**S**ource.

See if that fixes it.

**Comment by wedr2** [comment]
Also, if after 2 weeks from now and I still havent' heard back from you, I'll be closing this issue, and assume you have fixed the problem.

Deadline: July 3, 2016.

**Comment by NinjaBoyLao** [comment]
Shit im sorry man i got really busy really fast. got hauled into helping my girlfriends parents with some church stuff, it's not bad though, just time consuming. kids are cute man. ill see if that fixes it, gimme a bit

**Comment by tommai78101** [comment]
No problem. Deadline is extended to July 7, 2016.

**Comment by NinjaBoyLao** [comment]
Okay it doesn't fix it and i can run it again and show you the error bc i didn't screencap it i dont think. VBS is over, kids aren't cute anymore

**Comment by tommai78101** [comment]
What kind of error are you getting? Another possible suggestion is to not build the project within \path\to\devkitPro directory.

**Comment by tommai78101** [comment]
Any further updates on this issue? Will be closing this in 2 weeks, starting now.

Deadline: July 13, 2016.

**Comment by NinjaBoyLao** [comment]
I'm kinda just giving up, i'm very frustrated by my lack of understanding of these things. i feel about 2 years too late to be able to make some of my homebrew dreams (a good working Updater9, building in my own self-updaters to existing brews, and more) come true. so for now i thank you for this tutorial, i hope its useful to others, and im closing this

**Comment by wedr2** [comment]
Don't worry. You can try using Eclipse C/C++ instead when you feel like doing so.
