### ISSUE TITLE
Suggestion for quickly running 3dslink via F5 or Ctrl+F5

### ISSUE THREAD

**Issue by hourglasseye** [wedr2/Guide#2]
I wanted to comment on the Reddit threat, but its been archived so I'll just say it here.

![screenshot_011917_062908_pm](https://cloud.githubusercontent.com/assets/2950954/22103211/321ba8fa-de75-11e6-9d85-f223e0968474.jpg)

Can set the following in project properties:
* Configuration Properties -> Debugging -> Command to `C:\devkitPro\devkitARM\bin\3dslink.exe`
* Configuration Properties -> Debugging -> Command Arguments to `$(ProjectName).3dsx`

Then any of the following will send the built 3dsx to homebrew:
* Debug -> Start Debugging (F5)
* Debug -> Start without Debugging (Ctrl+F5)

What do you think?

**Comment by wedr2** [comment]
Thanks for your suggestion. I'll go ahead and review this and will update once I have something to say.

**Comment by wedr2** [comment]
Added to the wiki. Thanks again.
